name: Deploy Frontend

on:
  workflow_dispatch: # Enables manual triggering of workflow
  push:
    branches:
      - main
      - experiment/workflow

jobs:
  build:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker HUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image (with 'load' during testing)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          push: false # set to 'true' if this should be pushed to a registry
          load: true
          tags: zosorox/docker-react-tests:${{ github.sha }}

      - name: Run tests in Docker container
        run: |
          docker run -e CI=true zosorox/docker-react-tests:${{ github.sha }} npm test

      - # Temp fix to move/delete cache to it does not keep growing
        name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
